service: route-calculator

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 60
  stage: dev
  region: us-east-1

package:
  exclude:
    - .venv/**
    - venv/**

functions:
  hello:
    handler: src/main.handler
    events:
      - http:
          path: route-calculator
          method: post